@url_dev=http://localhost:3050/v1/api
@api_key=test_api_key

### test invalid url
GET {{url_dev}}/testxxx
x-api-key: {{api_key}}

### test middleware
GET {{url_dev}}/test
x-api-key: {{api_key}}


### sign up
POST {{url_dev}}/shop/signup
Content-Type: application/json
x-api-key: {{api_key}}

{   
    "name": "shop",
    "email": "shop@gmail.com",
    "password": "shop"
}

### login
POST {{url_dev}}/shop/login
Content-Type: application/json
x-api-key: {{api_key}}

{   
    "email": "shop@gmail.com",
    "password": "shop"
}